# Generated by Django 2.0.4 on 2019-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usn', models.CharField(max_length=10)),
                ('em', models.CharField(max_length=30)),
            ],
        ),
    ]
