# Generated by Django 2.0.4 on 2019-03-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='usn',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='create',
            old_name='em',
            new_name='cost',
        ),
    ]
