# Generated by Django 2.0.4 on 2019-03-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0002_auto_20190306_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='cost',
            new_name='money',
        ),
    ]
