# Generated by Django 2.0.4 on 2019-03-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0003_auto_20190307_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='money',
            new_name='cost',
        ),
    ]
