# Generated by Django 2.0.4 on 2019-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0004_auto_20190307_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='cost',
            field=models.CharField(max_length=50),
        ),
    ]
